Changes in Download Page.
zen-browser/www pull request #126
Opened 2024-08-28 06:51 UTC by aashirwadRunjan

1. Changed the choose you platform from conventional checkbox to light-looking. Looks good as it covers empty space without looking odd.
2. The box sizing in Choose your MacOS architecture was not even for AArch64 and INTEL.Fixed that issue to make it look even with windows and linux's.

2024-09-01 16:50 UTC, Jay-Karia requested changes

2024-09-01 16:50 UTC, Jay-Karia commented on package.json
No need to add additional dependencies and changing the version

2024-09-01 16:50 UTC, Jay-Karia commented on src/components/download.tsx
Please fix the formatting

2024-09-02 19:08 UTC, aashirwadRunjan commented on src/components/download.tsx
Done

2024-09-02 19:09 UTC, aashirwadRunjan commented on package.json
yes sure.Removed unwanted dependencies.

2024-09-02 19:33 UTC, mauro-balades commented
How does it look now?

2024-09-02 19:37 UTC, aashirwadRunjan commented
<img width="1440" alt="Screenshot 2024-09-03 at 1 05 37 AM" src="https://github.com/user-attachments/assets/2882cb56-b3c9-4352-86d5-f77b0516908e">
<img width="1440" alt="Screenshot 2024-09-03 at 1 05 43 AM" src="https://github.com/user-attachments/assets/dd3dcbb0-2d0e-46d4-81a2-4216ebf00d4e">

2024-09-02 19:38 UTC, aashirwadRunjan commented
The choose your platform was also very generic and this looks cooler IMO.
The box sizing of AArch64 and x64 Intel were uneven.

2024-09-02 19:46 UTC, mauro-balades commented
Nice, I really like it!

2024-09-03 03:32 UTC, Jay-Karia requested changes
`package-lock` file should also be reverted

2024-09-03 09:28 UTC, aashirwadRunjan commented
> `package-lock` file should also be reverted

Yes sure, have removed it.

2024-09-03 09:43 UTC, Jay-Karia commented on package-lock.json
?

2024-09-03 11:10 UTC, aashirwadRunjan commented on package-lock.json
still any issue?

2024-09-03 13:45 UTC, merged