Feat(footer): Add social links
zen-browser/www pull request #150
Opened 2024-08-31 18:57 UTC by lawlesx

Solved Issue - #94 

Updated the footer as per the design provided

![Screenshot 2024-08-31 235216](https://github.com/user-attachments/assets/a51cf12c-47c6-4d6b-82dd-d68bcdf4ba83)
![Screenshot 2024-08-31 235228](https://github.com/user-attachments/assets/ee560b41-7a4e-4d54-a8bc-a1fbe8b286c0)

2024-08-31 20:04 UTC, Jay-Karia commented on src/components/footer.tsx
For best practices,
The links array should be declared outside of JSX.

```
const links = [...]
```

2024-09-01 10:55 UTC, lawlesx commented on src/components/footer.tsx
Yeah, Sorry did it in a hurry.
Pushed a refactor.
Please take a look.

2024-09-01 11:32 UTC, Jay-Karia requested changes
The variable declared should be before the `return` statement

2024-09-01 11:44 UTC, lawlesx commented
😅 why is that? It's not dependent on anything so we can separate it from
the component.
Is some build failing?

On Sun, 1 Sept, 2024, 5:02 pm Jay, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The variable declared should be before the return statement
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/zen-browser/www/pull/150#pullrequestreview-2274354027>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMN76JJRN225SF6J6E2WWCDZUL3NZAVCNFSM6AAAAABNODEANWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZUGM2TIMBSG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-01 11:52 UTC, Jay-Karia commented
Take any JSX/TSX file (https://github.com/zen-browser/www/blob/main/src/components/marketplace.tsx)
The variables are always declared above the the return statement, however it does not change the result, but as mentioned earlier (for best practices).

Even the original code (with `lists` variable inside the jsx) did not broke the code.

2024-09-01 13:16 UTC, lawlesx commented
> Take any JSX/TSX file (https://github.com/zen-browser/www/blob/main/src/components/marketplace.tsx) The variables are always declared above the the return statement, however it does not change the result, but as mentioned earlier (for best practices).
> 
> Even the original code (with `lists` variable inside the jsx) did not broke the code.

I moved the social links to a separate file so later we can add more and the changes will reflect automatically

2024-09-01 13:18 UTC, Jay-Karia approved these changes

2024-09-01 13:18 UTC, lawlesx commented
@Jay-Karia Also added a `.vscode` config to remove unused import it will reduce the unnecessary import in the bundle

2024-09-01 19:26 UTC, mauro-balades commented
Could we do a rounded icon for discord? It looks out of place

2024-09-01 19:26 UTC, mauro-balades commented
Missclicked

2024-09-02 19:33 UTC, mauro-balades commented
Sorry, but i've changed the footer's design... but thanks!

2024-09-02 19:33 UTC, closed without merging

2024-09-03 02:42 UTC, lawlesx commented
> Sorry, but i've changed the footer's design... but thanks!

Was there a new design?